controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

adminer:
  path: /adminer
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /adminer/index.php
    permanent: true
