root:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /app
    permanent: true

controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

adminer:
  path: /adminer
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /adminer/index.php
    permanent: true

app:
  path: /app
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /app/index.html
    permanent: true

api_login_check:
  path: /api/auth/login
  methods: ["POST"]
