api_platform:
  title: SportGest API
  description: API pour la gestion de séances sportives
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
