nelmio_cors:
  defaults:
    origin_regex: false
    allow_origin: ["http://localhost:4200"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers:
      ["Content-Type", "Authorization", "X-Requested-With", "Accept", "Origin"]
    expose_headers: ["Set-Cookie"]
    allow_credentials: true
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["http://localhost:4200"]
      allow_headers:
        [
          "Content-Type",
          "Authorization",
          "X-Requested-With",
          "Accept",
          "Origin",
        ]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      expose_headers: ["Set-Cookie"]
      allow_credentials: true
      max_age: 3600
