services:
  # Base de données MariaDB
  db:
    image: mariadb:10.8
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  # Serveur PHP 8 avec Symfony (en mode dev)
  php:
    build:
      context: ../symfony
      dockerfile: Dockerfile
      target: dev
    env_file: .env
    volumes:
      - ../symfony/SportGest:/var/www/html
      - symfony_var:/var/www/html/var
      - symfony_vendor:/var/www/html/vendor
    ports:
      - "${PHP_PORT}:8000"
    depends_on:
      - db
  # Node.js pour Angular
  angular:
    build:
      context: ../angular
      dockerfile: Dockerfile
      target: dev
    env_file: .env
    working_dir: /SportGest
    volumes:
      - ../angular/SportGest:/SportGest
      - angular_node_modules:/SportGest/node_modules
    ports:
      - "${ANGULAR_PORT}:4200"

volumes:
  mariadb_data:
  angular_node_modules:
  symfony_var:
  symfony_vendor:
